import requests
import re

username = "shila.fastfood"

url = f"https://www.instagram.com/{username}/"

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/151.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}

response = requests.get(
    url,
    headers=headers,
    timeout=30
)

html = response.text

print("STATUS:", response.status_code)
print("SIZE:", len(html))


keys = [
    "__bbox",
    "server_payload",
    "profile_pic_url",
    "followers_count",
    "follower_count",
    "following_count",
    "biography",
    "profilePage",
    "user",
    "username",
    "PolarisViewer"
]


print("\n===== KEY SEARCH =====")

for key in keys:
    count = html.lower().count(key.lower())
    print(key, ":", count)


print("\n===== JSON SCRIPT BLOCKS =====")

blocks = re.findall(
    r'<script[^>]*>(.*?)</script>',
    html,
    re.DOTALL
)

print("SCRIPT COUNT:", len(blocks))

for i, block in enumerate(blocks):

    if any(k.lower() in block.lower() for k in [
        "followers_count",
        "biography",
        "profile_pic_url",
        "follower_count"
    ]):

        print("\nFOUND BLOCK:", i)
        print(block[:3000])
