name: Instagram Profile Test

"on":
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: |
          pip install requests

      - name: Test Instagram
        run: |
          python - <<'PY'
          import requests

          username = "shila.fastfood"

          url = f"https://www.instagram.com/{username}/"

          headers = {
              "User-Agent": "Mozilla/5.0"
          }

          r = requests.get(
              url,
              headers=headers,
              timeout=30
          )

          print("STATUS:", r.status_code)
          print("SIZE:", len(r.text))

          html = r.text

          keys = [
              "__bbox",
              "server_payload",
              "profile_pic_url",
              "followers_count",
              "biography",
              "username",
              "PolarisViewer"
          ]

          print("===== KEY SEARCH =====")

          for key in keys:
              print(key, ":", html.lower().count(key.lower()))

          PY
